name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    uses: anyshift-io/custom_github_actions/.github/workflows/reusable-dependabot-auto-merge.yml@main
    secrets: inherit
